//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_TASK_DATA_ACCESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TASK
    {
        public T_TASK()
        {
            this.T_USER_TASK = new HashSet<T_USER_TASK>();
        }
    
        public int TASK_ID { get; set; }
        public string TASK_NAME { get; set; }
        public byte TASK_LEVEL { get; set; }
        public string TASK_CONTENT { get; set; }
        public Nullable<int> TASK_REWARD_MONEY { get; set; }
        public string TASK_REWARD_OTHER { get; set; }
        public int VIEW_COUNT { get; set; }
        public byte TASK_STATUS { get; set; }
        public Nullable<double> TIME_TO_FINISH { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public bool DELETE_FLAG { get; set; }
        public string CREATE_USER_NAME { get; set; }
        public string OWN_USER_ID { get; set; }
        public string OWN_USER_NAME { get; set; }
    
        public virtual T_USER T_USER { get; set; }
        public virtual ICollection<T_USER_TASK> T_USER_TASK { get; set; }
    }
}
