//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_TASK_DATA_ACCESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_TASK
    {
        public int SQUENCE_ID { get; set; }
        public string USER_TAKE_ID { get; set; }
        public int TASK_ID { get; set; }
        public byte TASK_STATUS { get; set; }
        public string CREATE_USER_NAME { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public bool DELETE_FLAG { get; set; }
    
        public virtual T_TASK T_TASK { get; set; }
        public virtual T_USER T_USER { get; set; }
    }
}
