//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_TASK_DATA_ACCESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        public T_USER()
        {
            this.T_TASK = new HashSet<T_TASK>();
            this.T_USER_TASK = new HashSet<T_USER_TASK>();
        }
    
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public short USER_LEVEL { get; set; }
        public byte USER_ROLE { get; set; }
        public bool BLOCK_FLAG { get; set; }
        public bool DELETE_FLAG { get; set; }
    
        public virtual ICollection<T_TASK> T_TASK { get; set; }
        public virtual ICollection<T_USER_TASK> T_USER_TASK { get; set; }
    }
}
